config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'transactions', to: 'transactions#fetch'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def fetch
    @zip_code = params.require(:zip_code)
    @resp = JSON.parse(Typhoeus.get("http://api.cquest.org/dvf?code_postal=#{@zip_code}").response_body)['resultats']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home Pricer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Home pricer</h1>
    <br />
    <br />
    <%= yield %>
  </body>
</html>

app/views/transactions/fetch.html.erb
<%= link_to '< Retour', welcome_index_path, method: :get %>
<br />
<br />
Transactions enregistrées dans la commune : <%= @zip_code %>
<br />
<table border=1>
  <tr>
    <th>Date</th>
    <th>Adresse</th>
    <th>Type</th>
    <th>Surface bâti</th>
    <th>Surface terrain</th>
    <th>Nombre pièces</th>
    <th>Valeur</th>
  </tr>
  <% @resp.each do |result| %>
      <tr>
        <td><%= result['date_mutation']%></td>
        <td><%= "#{result['numero_voie']} #{result['type_voie']} #{result['voie']}, #{result['code_postal']} #{result['commune']}"%></td>
        <td><%= result['type_local']%></td>
        <td><%= result['surface_relle_bati']%></td>
        <td><%= result['surface_terrain']%></td>
        <td><%= result['nombre_pieces_principales']%></td>
        <td><%= result['valeur_fonciere']%> €</td>
      </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<%= form_with url: transactions_path, method: :post do |form| %>
    <%= form.label :zip_code, "Code postal" %>
    <%= form.text_field :zip_code %>
    <%= submit_tag 'Afficher les transactions' %>
<% end %>